# Generated by Django 5.2.7 on 2025-10-25 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('lugar', models.CharField(max_length=255, verbose_name='Lugar')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Imagen')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Entrada')),
                ('plazas_totales', models.IntegerField(default=0, verbose_name='Plazas Totales')),
                ('plazas_disponibles', models.IntegerField(default=0, verbose_name='Plazas Disponibles')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrado')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
